
@baseUrl = https://proyecto-backend-beta.vercel.app/api/publications
# Lista base 
GET {{baseUrl}}
### 
 
# Obetener uno por id 
GET {{baseUrl}}/2
### 
 
# Crear uno nuevo 
POST {{baseUrl}}
Content-Type: application/json 

{
  "title": "Laptop Hp",
  "description": "Laptop usada en buen estado",
  "price": 1500,
  "category": "Tecnología",
  "condition": "Usado",
  "image": "laptop.jpg",
  "location": "Lima",
  "whatsapp": "999888777",
  "sellerId": "123",
  "sellerName": "Mauricio"
}

### 
# Actualizar (el precio) 
PUT {{baseUrl}}/1 
Content-Type: application/json 

{
    "id": 1 ,
    "title": "Laptop Hp Actualizada", 
    "description": "Laptop usada en buen estado", 
    "price": 1600, 
    "category": "Tecnología", 
    "condition": "Usado", 
    "image": "laptop.jpg", 
    "location": "Lima", 
    "whatsapp": "999888777", 
    "sellerId": "123", 
    "sellerName": "Mauricio"
} 

###  
# Eliminar 
DELETE {{baseUrl}}/1