@baseUrl = https://proyecto-backend-beta.vercel.app/api/user
POST {{baseUrl}}/register 
Content-Type: application/json 

{
    "username": "Fernanda",
    "email": "20233256@aloe.ulima.edu.pe",
    "password": "123456"
}

### 
# Login
POST {{baseUrl}}/login
Content-Type: application/json 

{
    "email": "20233256@aloe.ulima.edu.pe",
    "password": "123456"
}

###
# Perfil de usuario 
GET {{baseUrl}}/profile
